# ════════════════════════════════════════════════
#  fuzzel · launcher — Caelestia-inspired
# ════════════════════════════════════════════════

[main]
font=JetBrainsMono Nerd Font:size=13
dpi-aware=auto
prompt= 
placeholder=Buscar aplicación…
width=30
lines=8
tabs=4
horizontal-pad=20
vertical-pad=10
inner-pad=6
exit-on-kb-focus-loss=yes
icons-enabled=yes
icon-theme=Papirus-Dark
match-mode=fzf

[colors]
background=1e1e2edd
text=cdd6f4ff
match=f9e2afff
selection=313244ff
selection-text=f9e2afff
selection-match=f9e2afff
border=f9e2af44ff

[border]
width=1
radius=12

[key-bindings]
# Los defaults de fuzzel son suficientes
