# ════════════════════════════════════════════════
#  foot · terminal — Caelestia-inspired
#  Transparencia 85 % · blur vía SwayFX
# ════════════════════════════════════════════════

[main]
term            = foot
shell           = zsh
login-shell     = no
font            = JetBrainsMono Nerd Font:size=11
dpi-aware       = yes
pad             = 12x8
notify          = notify-send -a foot -i foot ${title} ${body}

[scrollback]
lines           = 5000
multiplier      = 3.0

[url]
launch          = xdg-open ${url}
osc8-underline  = url-mode

[cursor]
style           = beam
blink           = yes

[mouse]
hide-when-typing = yes

[colors]
# Transparencia 85 % — el blur lo aplica SwayFX
alpha           = 0.85
alpha-applies-to = default

# Paleta Catppuccin Mocha
foreground      = cdd6f4
background      = 1e1e2e

regular0        = 45475a   # black
regular1        = f38ba8   # red
regular2        = a6e3a1   # green
regular3        = f9e2af   # yellow  ← acento focal
regular4        = 89b4fa   # blue
regular5        = cba6f7   # magenta
regular6        = 94e2d5   # cyan
regular7        = bac2de   # white

bright0         = 585b70
bright1         = f38ba8
bright2         = a6e3a1
bright3         = f9e2af
bright4         = 89b4fa
bright5         = cba6f7
bright6         = 94e2d5
bright7         = a6adc8

selection-foreground = cdd6f4
selection-background = 45475a

[key-bindings]
# Ajustes de fuente
font-increase   = Control+equal
font-decrease   = Control+minus
font-reset      = Control+0
# Portapapeles
clipboard-copy  = Control+Shift+c
clipboard-paste = Control+Shift+v
